---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app-redis
  namespace: weather-app
  labels:
    project: ipgeolocation
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      project: weather-app
      app: redis
  template:
    metadata:
      labels:
        project: weather-app
        app: redis
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: project
                operator: In
                values:
                - weather-app
              - key: app
                operator: In
                values:
                - redis
      tolerations:
      - key: "redis"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379