---
apiVersion: v1
kind: Service
metadata:
  name: weather-app-redis
  namespace: weather-app
  labels:
    project: weather-app
    app: redis
spec:
  type: ClusterIP
  selector:
    project: weather-app
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP