---
apiVersion: v1
kind: Secret
metadata:
  name: weather-api-secret
  namespace: weather-app
  labels:
    project: weather-app
    app: api
type: Opaque
data:
  API_KEY: a12b65b9c37eab5f4e8ba52db5b532b4